spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    hikari.maximum-pool-size: 1
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
server.port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
